### PR TITLE
Incomplete Form Tests

### PR DESCRIPTION
**Pull request by nsclark**

### CODE REVIEW

**Comment by nsclark** [comment]
@phillipm ahh.. so I messed up branch 35 in trying to resolve the merge conflicts. Am looking into what I did wrong/how to correct. However, since we're trying to freeze today, I started a new branch that shouldn't have any merge conflicts that also has the recommended changes. I apologize if that makes this more difficult to review or isn't good workflow.

**Comment by phillipm** [comment]
No worries. The 2 `.rb` files in this PR are not in the correct directory. They should be in `features/step_definitions`

**Comment by nsclark** [comment]
Wow, yea, it's a Friday. Corrected.

**Comment by phillipm** [comment]
@nsclark Hey, sorry to hijack your PR. I was testing it out and intended to make a few changes and then continue leaving feedback. But I kept digging myself deeper and deeper into changes, so I figured it easier to just continue working on it.

**Comment by nsclark** [comment]
@phillipm No problem at all. It's really helpful to see the changes you're making, so thank you. Hopefully I didn't leave too much for you to have to correct and the changes didn't take you too long. Let me know if you still think there is some work to be done though and I can help out.

**Pull request merged**
