### PR TITLE
Build tests pipeline

### PR DESCRIPTION
**Pull request by wpride**
@amstone326 This removes the need for the `commcare-odk-build-tests` job and resolves the branching issue

### CODE REVIEW

**Comment by amstone326** [comment]
Sweet, this is awesome. Is there anything that should change in the `ui-test-pipeline` job after I merge this?

**Comment by amstone326** [comment]
And can this job be deleted now? https://jenkins.dimagi.com/job/commcare-odk-build-tests/

**Comment by wpride** [comment]
@amstone326 deleted that job, and confirming that nothing needs to change in the `ui-test-pipeline` job. The nice thing about pipeline is that ~all changes will be encapsulated in the source code meaning jobs should rarely need to be configured in the Jenkins UI

**Comment by amstone326** [comment]
Great, that makes sense.

**Pull request merged**
